apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
      - name: video-service
        image: coreychen4444/shortvideo_video:v1.0
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: video-service
